spring:
 datasource:  # 数据源配置
  type: com.alibaba.druid.pool.DruidDataSource		# 当前数据源操作类型
  driver-class-name: org.gjt.mm.mysql.Driver		# mysql驱动包
  url: jdbc:mysql://localhost:3306/spider_cpquery		#  数据库名称
  username: root
  password: root
  dbcp2:
   min-idle: 5									# 数据库连接池的最小维持连接数
   initial-size: 5								# 初始化连接数
   max-total: 5									# 最大连接数	
   max-wait-millis: 200							# 等待连接获取的最大超时时间
 mail:  # 邮件配置
  host: smtp.126.com
  username: yutian1012@126.com
  password: 
  default-encoding: UTF-8
 redis: # redis配置
  database: 0
  host: 127.0.0.1
  password: 123456
  port: 6379
  timeout: 3000
  pool:
   max-idle: 500
   min-idle: 50
   max-active: 2000
   max-wait: 1000
  
mail: # 自定义信息配置
 fromMail:
  addr: yutian1012@126.com 
 toReportMail:
  addr: yutian1012@126.com
 reportTemplate: mail/pageReportTemplate
 
info: # 测试覆盖问题
 app.name: spider-dev